version: "3.6"
services:
    rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password        
        image: rabbitmq:3-management
                
    customerapi:
        container_name: customerapi
        ports:
            - 8001:80
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
        build:
            context: ./CustomerApi
            dockerfile: CustomerApi/Dockerfile.Build
        restart: on-failure        
        depends_on:
            - rabbitmq
        
    orderapi:
        container_name: order
        ports:
            - 8000:80
            - 9001:443
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"       
        build:
            context: ./OrderApi      
            dockerfile: OrderApi/Dockerfile.Build
        restart: on-failure
        depends_on:
            - rabbitmq
                        