name: terraform create custom

on:
    
  workflow_dispatch:
    inputs:
      TerraformFolder:
        type: choice
        description: 'Relative Path For Terraform Folder To Create'     
        required: true
        default: 'registry'  
        options:
        - registry
        - mssql
        - app
        - servicebus

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_ID }}
  ARM_ACCESS_KEY: ${{ secrets.AZURE_ACCESS_KEY }}
  TF_FOLDER: "${{ github.event.inputs.TerraformFolder }}"
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
  CONNECTIONSTRING_CUSTOMER: ${{ secrets.SQLSERVER_CONNECTIONSTRING_CUSTOMER }}
  CONNECTIONSTRING_ORDER: ${{ secrets.SQLSERVER_CONNECTIONSTRING_ORDER }}  

jobs:
  resource-create:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7       

      - name: az login
        run: |
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az account set --subscription $ARM_SUBSCRIPTION_ID
          

      - name: terraform apply
        run: |
          echo ${{env.TF_FOLDER}} 
          terraform init -var access_key=$ARM_ACCESS_KEY -var tenant_id=$ARM_TENANT_ID -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID
          if [[ ${{env.TF_FOLDER}} == "app" ]]
           then
             terraform destroy --auto-approve -var docker_registry_password="$CONTAINER_REGISTRY_PASSWORD" -var customer_connection="$CONNECTIONSTRING_CUSTOMER" -var order_connection="$CONNECTIONSTRING_ORDER" -var access_key=$ARM_ACCESS_KEY -var tenant_id=$ARM_TENANT_ID -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID
             terraform apply --auto-approve -var docker_registry_password="$CONTAINER_REGISTRY_PASSWORD" -var customer_connection="$CONNECTIONSTRING_CUSTOMER" -var order_connection="$CONNECTIONSTRING_ORDER" -var access_key=$ARM_ACCESS_KEY -var tenant_id=$ARM_TENANT_ID -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID
           else
             terraform destroy --auto-approve -var access_key=$ARM_ACCESS_KEY -var tenant_id=$ARM_TENANT_ID -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID
             terraform apply --auto-approve -var access_key=$ARM_ACCESS_KEY -var tenant_id=$ARM_TENANT_ID -var client_id=$ARM_CLIENT_ID -var client_secret=$ARM_CLIENT_SECRET -var subscription_id=$ARM_SUBSCRIPTION_ID
          fi
        working-directory: ./terraform/${{env.TF_FOLDER}}

      - name: customerapp identity assign
        run: |
          if($TF_FOLDER -eq "app"){
            $app_identity = az webapp identity assign --name "customerapi-app" --resource-group "rg-app-container"
            $app_identity = $app_identity | ConvertFrom-Json
            az keyvault set-policy --name ozzkeyvault --object-id $app_identity.principalId --secret-permissions get list
          } 
        shell: pwsh        