name: terraform scheduled destroy

on:
  schedule:
    - cron: "0 18 * * *"
    
    
  workflow_dispatch:  

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_ID }}
  ARM_ACCESS_KEY: ${{ secrets.AZURE_ACCESS_KEY }}
  TF_FOLDER: "${{ github.event.inputs.TerraformFolder }}"  
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
  CONNECTIONSTRING_CUSTOMER: ${{ secrets.SQLSERVER_CONNECTIONSTRING_CUSTOMER }}
  CONNECTIONSTRING_ORDER: ${{ secrets.SQLSERVER_CONNECTIONSTRING_ORDER }}
  SERVICEBUS_TOKEN: ${{ secrets.AZURE_SERVICEBUS_TOKEN }}

jobs:
  resources-destroy:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7       

      - name: run powershell script
        run: ./destroy.ps1
        shell: pwsh
        working-directory: ./terraform